import "./globals.css";

import { ModalProvider } from "@/modal-stack/modal-provider";

import { FirstModalShell } from "@/components/first-modal/shell";
import { FirstModalComponent } from "@/components/first-modal/component";
import { SecondModalShell } from "@/components/second-modal/shell";
import { SecondModalComponent } from "@/components/second-modal/component";
import { ThirdModalShell } from "@/components/third-modal/shell";
import { ThirdModalComponent } from "@/components/third-modal/component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ModalProvider>
          {children}

          <FirstModalShell>
            <FirstModalComponent />
          </FirstModalShell>

          <SecondModalShell>
            <SecondModalComponent />
          </SecondModalShell>

          <ThirdModalShell>
            <ThirdModalComponent />
          </ThirdModalShell>
        </ModalProvider>
      </body>
    </html>
  );
}
